version: '3.5'

services:

  zookeeper_ch:
    image: zookeeper:3.8.0-temurin
    container_name: zookeeper_ch
    hostname: zookeeper_ch
    networks:
      - movies

  clickhouse-node1:
    image: yandex/clickhouse-server:21.3.20.1-alpine
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/node1:/etc/clickhouse-server
      - ./etl/ch_config:/etc/clickhouse-server/config.d
    depends_on:
      - zookeeper_ch
    networks:
      - movies

  clickhouse-node2:
    image: yandex/clickhouse-server:21.3.20.1-alpine
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./data/node2:/etc/clickhouse-server
      - ./etl/ch_config:/etc/clickhouse-server/config.d
    depends_on:
      - zookeeper_ch
    networks:
      - movies

  clickhouse-node3:
    image: yandex/clickhouse-server:21.3.20.1-alpine
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    volumes:
      - ./data/node3:/etc/clickhouse-server
      - ./etl/ch_config:/etc/clickhouse-server/config.d
    depends_on:
      - zookeeper_ch
    networks:
      - movies

  clickhouse-node4:
    image: yandex/clickhouse-server:21.3.20.1-alpine
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./data/node4:/etc/clickhouse-server
      - ./etl/ch_config:/etc/clickhouse-server/config.d
    depends_on:
      - zookeeper_ch
    networks:
      - movies