version: '3.5'

services:
  ugc:
    container_name: ugc
    image: ugc
    networks:
      - movies
    environment:
      KAFKA__HOST: broker
      KAFKA__PORT: 29092
      APP__JWT_SECRET_KEY: $APP__JWT_SECRET_KEY
      APP__ALGORITHM: HS256
    depends_on:
      - broker
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - movies
    depends_on:
      - ugc


networks:
    movies:
      name: movies

volumes:
    postgres:
    pgadmin: