name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide flake8-html mypy lxml

      - name: Create reports folders
        run: |
          mkdir -p reports/wemake/
          mkdir -p reports/mypy/

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./src/service --count --select=E9,F63,F7,F82 --show-source --statistics 
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./src/service --exit-zero --max-complexity=10 --max-line-length=127 --format=html --htmldir=reports/wemake/

      - name: Lint with mypy
        run: |
          mypy ./src/service --html-report reports/mypy/ --follow-imports silent

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports/

  unit_tests:
    needs: code_quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/service/tests/requirements.txt
        if [ -f src/service/requirements.txt ]; then pip install -r src/service/requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest src/service/tests/unit

    - name: Send telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Be happy, don`t worry for deploy on python-${{ matrix.python_version }}

